// Extracted from Main.vue to avoid Vue SFC compiler issues with HTML in template literals
// 进度条动画参数与任务卡片共用（唯一实现），注入到窗口脚本里
import {
  PROGRESS_BACKWARD_TOLERANCE,
  PROGRESS_EASE_ALPHA,
  PROGRESS_LEAD_ALMOST_DONE,
  PROGRESS_LEAD_MAX,
  PROGRESS_LEAD_NEAR_DONE,
  PROGRESS_NEAR_DONE_AT,
  PROGRESS_ALMOST_DONE_AT,
  PROGRESS_TICK_MS,
  PROGRESS_BAR_CSS_TRANSITION
} from '@shared/utils/progress-easing'

export function buildProgressWindowHtml (useCustomFrame, isMac, getThemeColors) {
 {
        const tc = getThemeColors()
        const bodyBg = tc.bodyBg
        const textColor = tc.textColor
        const statusColor = tc.statusColor
        const metaColor = tc.metaColor
        const barBg = tc.barBg
        const controlsBg = tc.controlsBg
        const controlsBorder = tc.controlsBorder
        const controlsDivider = tc.controlsDivider
        const controlsItemColor = tc.controlsItemColor
        const controlsItemHoverBg = tc.controlsItemHoverBg
        const titleBtnHoverBg = tc.titleBtnHoverBg
        const indicatorBg = tc.indicatorBg
        const primaryColor = tc.primaryColor
        // 下方控制区所有控件的圆角（按钮/分段组/滑块指示块/输入框/保存键）。
        // 整排是同一套"圆角方块"（不是圆形）。要统一调大/调小只改这一处。
        const controlRadius = '10px'
        // macOS 标题栏右侧留白。**与「下载完成」弹窗各自独立**：那个窗口的标题
        // 右间距是它自己的事，改它不该带到这个窗口来（用户点名过）。这里保持原值。
        const titleRightInset = '8px'
        const showTitleBar = useCustomFrame || isMac
        const titleBarStyle = showTitleBar
          ? `.title-bar{height:26px;display:flex;align-items:center;justify-content:space-between;padding:0 16px;padding-left:${isMac ? '78px' : '16px'};-webkit-app-region:drag;background-color:VAR_BODY_BG;}`
          : '.title-bar{display:none;}'
        const contentStyle = showTitleBar
          ? '.content{box-sizing:border-box;padding:0 12px 12px 12px;height:calc(100vh - 26px);overflow-y:auto;}'
          : '.content{box-sizing:border-box;padding:0 12px 12px 12px;height:100vh;overflow-y:auto;}'
        const styles = [
          'body{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:12px;color:VAR_TEXT_COLOR;background-color:VAR_BODY_BG;overflow:hidden;}',
          '::-webkit-scrollbar{width:8px;height:8px;}',
          '::-webkit-scrollbar-thumb{border-radius:8px;background-color:rgba(0,0,0,0.4);}',
          '::-webkit-scrollbar-thumb:window-inactive{background-color:rgba(0,0,0,0.25);}',
          '::-webkit-scrollbar-corner{background:transparent;}',
          titleBarStyle,
          contentStyle,
          '.title-text{font-size:12px;opacity:0.85;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-right:8px;}',
          '.title-actions{display:flex;gap:4px;-webkit-app-region:no-drag;}',
          '.title-btn{width:18px;height:18px;border-radius:3px;border:none;background:transparent;color:VAR_TEXT_COLOR;cursor:pointer;padding:0;font-size:14px;line-height:18px;}',
          '.title-btn:hover{background-color:VAR_TITLE_BTN_HOVER_BG;}',
          ...(isMac
            ? [
              `.title-bar{justify-content:flex-end !important;padding-top:6px;padding-right:${titleRightInset};}`,
              '.title-actions{display:none !important;}'
            ]
            : []),
          '.tab-content{display:none;}',
          '.tab-content.active{display:block;}',
          '.bar{height:6px;background:VAR_BAR_BG;border-radius:3px;overflow:hidden;margin-bottom:8px;}',
          '.bar-fixed{position:fixed;top:160px;left:12px;right:12px;height:6px;background:VAR_BAR_BG;border-radius:3px;overflow:hidden;z-index:999;transition:background-color .35s ease;}',
          /* 与主窗口任务卡片进度条 (TaskProgress.vue + Theme/Default.scss) 一致：
             内条两端圆角（右侧不再是直角），过渡曲线/时长也来自
             @shared/utils/progress-easing 的同一个常量。
             两层都是绝对定位铺满轨道，宽度/颜色/透明度都走过渡 —— 这样
             "下载 → 待合并（黄） → 合并（绿盖） → 已完成（绿底）"没有一处瞬变。 */
          `.bar-inner{position:absolute;left:0;top:0;height:100%;background:#1a7fe0;width:0;border-radius:3px;transition:${PROGRESS_BAR_CSS_TRANSITION}, background-color .4s ease, opacity .4s ease;}`,
          '.bar-inner--cover{z-index:1;background:#2ACB42;}',
          /* 直播三态（与任务卡片 TaskProgress.vue 的 .is-live 同一套）：录制中 =
             红系滚动斜纹（相位由 JS 推进，见 recStep）；停住 = 减速并交叉淡化到
             "暂停灰"；完成 = 斜纹淡出、绿色内条铺满。两端 10px 渐隐遮罩让斜纹
             进出时淡出，边缘不会出现细刺。stops 6.364/12.728px ⇒ 沿 x 轴周期
             恰 18px（相位取模 18px 即无缝循环） */
          '.bar.is-live,.bar-fixed.is-live{position:relative;}',
          '.bar.is-live::before,.bar.is-live::after,.bar-fixed.is-live::before,.bar-fixed.is-live::after{content:"";position:absolute;inset:0;border-radius:inherit;background-position:var(--lc-rec-phase,0px) 0;transition:opacity .45s ease;pointer-events:none;mask-image:linear-gradient(90deg,transparent 0,#000 10px,#000 calc(100% - 10px),transparent 100%);-webkit-mask-image:linear-gradient(90deg,transparent 0,#000 10px,#000 calc(100% - 10px),transparent 100%);}',
          '.bar.is-live::before,.bar-fixed.is-live::before{background-image:repeating-linear-gradient(-45deg,rgba(245,108,108,0.9) 0 6.364px,rgba(245,108,108,0.22) 6.364px 12.728px);opacity:1;}',
          '.bar.is-live::after,.bar-fixed.is-live::after{background-image:repeating-linear-gradient(-45deg,rgba(115,115,115,0.8) 0 6.364px,rgba(115,115,115,0.2) 6.364px 12.728px);opacity:0;}',
          '.bar.is-rec-stopped::before,.bar-fixed.is-rec-stopped::before{opacity:0;}',
          '.bar.is-rec-stopped::after,.bar-fixed.is-rec-stopped::after{opacity:1;}',
          '.bar.is-rec-done::before,.bar.is-rec-done::after,.bar-fixed.is-rec-done::before,.bar-fixed.is-rec-done::after{opacity:0;}',
          '.meta{color:VAR_META_COLOR;font-size:12px;margin-bottom:8px;}',          '.meta-line{margin-bottom:2px;}',
          '.pieces-scroll-wrap{position:relative;margin-bottom:8px;}',
          '.pieces-empty{padding:28px 0;text-align:center;font-size:12px;color:VAR_META_COLOR;user-select:none;}',
          '.pieces-scroll-box{max-height:120px;overflow-y:auto;overflow-x:hidden;cursor:grab;user-select:none;-webkit-user-select:none;scrollbar-width:thin;scrollbar-color:rgba(0,0,0,0.15) transparent;}',
          '.pieces-scroll-box.is-dragging{cursor:grabbing;}',
          '.pieces-scroll-box::-webkit-scrollbar{width:6px;}',
          '.pieces-scroll-box::-webkit-scrollbar-track{background:transparent;}',
          '.pieces-scroll-box::-webkit-scrollbar-thumb{background:rgba(0,0,0,0.15);border-radius:3px;}',
          '.pieces-bar{display:flex;flex-wrap:wrap;gap:3px;}',
          '.piece{width:10px;height:10px;border-radius:4px;}',
          '.piece.s0{background:VAR_PIECE_COLOR_0;}',
          '.piece.s1{background:VAR_PIECE_COLOR_1;}',
          '.piece.s2{background:VAR_PIECE_COLOR_2;}',
          '.piece.s3{background:VAR_PIECE_COLOR_3;}',
          '.piece.s4{background:VAR_PIECE_COLOR_4;}',
          /* s5 = 未选择（该格分片属于未勾选的文件，不会下载） */
          '.piece.s5{background:VAR_PIECE_COLOR_5;}',
          '.pieces-fade{position:absolute;left:0;right:0;height:16px;pointer-events:none;z-index:2;}',
          '.pieces-fade--top{top:0;background:linear-gradient(to bottom,VAR_BODY_BG 0%,transparent 100%);}',
          '.pieces-fade--bottom{bottom:0;background:linear-gradient(to top,VAR_BODY_BG 0%,transparent 100%);}',
          '.conn-summary{display:flex;gap:16px;margin-bottom:10px;padding:8px;background:VAR_BAR_BG;border-radius:0;}',
          '.conn-summary-item{text-align:center;flex:1;min-width:0;}',
          '.conn-summary-label{font-size:11px;color:VAR_META_COLOR;margin-bottom:2px;white-space:nowrap;}',
          '.conn-summary-value{font-size:14px;font-weight:600;white-space:nowrap;}',
          '.conn-table-wrap{-webkit-app-region:no-drag;max-height:120px;overflow-y:auto;overflow-x:hidden;}',
          '.conn-table{width:100%;border-collapse:collapse;font-size:11px;background:transparent;table-layout:fixed;}',
          '.conn-table th,.conn-table td{padding:4px 6px;text-align:left;border:none;white-space:nowrap;}',
          '.conn-table th{background:transparent;font-weight:500;position:sticky;top:0;color:VAR_TEXT_COLOR;}',
          '.conn-table td{color:VAR_META_COLOR;background:transparent;}',
          '.conn-table .speed-active{color:#67c23a;font-weight:500;}',
          '.conn-table td:nth-child(2),.conn-table th:nth-child(2){width:76px;text-align:right;}',
          '.conn-table td:nth-child(3),.conn-table th:nth-child(3){width:78px;text-align:right;}',
          '.conn-table td:nth-child(4),.conn-table th:nth-child(4){width:60px;text-align:right;}',
          '.conn-host{display:block;max-width:100%;white-space:nowrap;overflow:hidden;text-overflow:clip;-webkit-mask-image:linear-gradient(to right,rgba(0,0,0,1) 0%,rgba(0,0,0,1) calc(100% - 18px),rgba(0,0,0,0) 100%);mask-image:linear-gradient(to right,rgba(0,0,0,1) 0%,rgba(0,0,0,1) calc(100% - 18px),rgba(0,0,0,0) 100%);}',
          '.host-tooltip{position:fixed;left:0;top:0;display:none;max-width:420px;white-space:normal;word-break:break-all;padding:6px 8px;border-radius:6px;background:rgba(0,0,0,0.78);color:#fff;font-size:12px;line-height:1.25;pointer-events:none;z-index:3000;box-shadow:0 6px 18px rgba(0,0,0,0.25);}',
          '.conn-empty{text-align:center;padding:20px;color:VAR_META_COLOR;}',
          '.connections-panel{position:fixed;top:220px;left:0;right:0;padding:12px 0;background-color:VAR_BODY_BG;box-sizing:border-box;}',
          // 左侧那组固定贴住窗口左边缘（与上方进度条的 left:12px 对齐）；右侧那组
          // 用 margin-left:auto 顶到右边缘。两组之间用 flex gap 8px —— 这样相邻
          // 控件的间距和组内间距**一致**（原来是 space-between，余量全塞进中间，
          // 窗口窄时中间那段看起来比其它间距大）。
          '.controls{position:fixed;top:170px;left:12px;right:12px;display:flex;align-items:center;gap:8px;padding:8px 0;background-color:VAR_BODY_BG;pointer-events:none;z-index:1000;}',
          '.controls-left{display:flex;pointer-events:auto;}',
          '.controls-left .controls-btn{position:relative;}',
          // connToggle 与 pinBtn 视觉上组成一个药丸按钮组（pinBtn 以负 margin 叠在
          // connToggle 下方）。若只给 connToggle 自身加 hover，悬停到 pinBtn 露出的
          // 右半部分时不会高亮，出现"只有一边高亮"。改为对 .controls-left 整组 hover：
          // 任意一侧悬停时两侧同时高亮，保持整体一致。
          '.controls-left:hover .controls-btn{background-color:VAR_CONTROLS_ITEM_HOVER_BG;}',
          '.controls-left:hover #pinBtn{background-color:VAR_CONTROLS_ITEM_HOVER_BG;}',
          // 分段切换**吃掉左右两组之间的余量**（flex-grow:1）：只有这样它的
          // 左右两侧才恒等于 flex gap 的 8px。以前它是内容宽度、余量由
          // `.controls-inner{margin-left:auto}` 全塞到它右侧 —— 窗口固定 360px，
          // 内容宽度随 tab 文案/数量变化，那 4~50px 的余量就全变成了"分类切换右边
          // 多出来的间距"（用户两次点名）。宽度由它自己吸收后，无论 2 个还是 3 个
          // tab、无论哪种语言，相邻间距都是 8px。
          '.pieces-toggle-group{display:none;background-color:VAR_CONTROLS_BG;border-radius:VAR_CTRL_RADIUS;box-shadow:0 2px 8px rgba(0,0,0,0.15);border:1px solid VAR_CONTROLS_BORDER;overflow:hidden;position:relative;pointer-events:auto;-webkit-app-region:no-drag;flex:1 1 auto;min-width:0;}',
          '.pieces-toggle-indicator{position:absolute;height:32px;top:2px;left:0;width:0;background-color:VAR_PRIMARY_COLOR;border-radius:VAR_CTRL_RADIUS;transition:transform 0.25s cubic-bezier(0.4,0,0.2,1),width 0.25s ease;z-index:0;}',
          // 内边距必须**左右对称**（曾为 `0 12px 0 8px`）：不对称时整组右侧
          // 的留白比左侧多 4px，看上去就是"分类切换右侧间距多了"。
          // flex:1 让各 tab 均分整组宽度，文字自带居中 → 左右留白永远相等。
          '.pieces-toggle-tab{border:none;box-shadow:none;margin:0;background-color:transparent;height:36px;padding:0 8px;font-size:12px;color:VAR_CONTROLS_ITEM_COLOR;cursor:pointer;position:relative;z-index:1;transition:color 0.2s ease;white-space:nowrap;flex:1 1 auto;min-width:0;overflow:hidden;text-overflow:ellipsis;}',
          '.pieces-toggle-tab:hover:not(.active){color:VAR_PRIMARY_COLOR;}',
          '.pieces-toggle-tab.active{color:#fff;}',
          '#pinBtn{margin-left:-18px;z-index:1;border-radius:0 VAR_CTRL_RADIUS VAR_CTRL_RADIUS 0;width:46px;background-color:VAR_CONTROLS_BG;}',
          '#connToggle{z-index:2;}',
          '.controls-inner{display:flex;align-items:center;justify-content:flex-end;gap:8px;pointer-events:auto;margin-left:auto;}',
          '.controls-divider{display:none;}',
          '.settings-panel{padding:2px 2px 4px 2px;}',
          '.settings-row{display:flex;align-items:center;gap:8px;margin-bottom:8px;}',
          '.settings-label{font-size:12px;color:VAR_META_COLOR;min-width:64px;white-space:nowrap;}',
          '.settings-select{height:26px;box-sizing:border-box;border:1px solid VAR_CONTROLS_BORDER;border-radius:VAR_CTRL_RADIUS;background-color:VAR_CONTROLS_BG;color:VAR_TEXT_COLOR;font-size:12px;padding:0 4px;outline:none;width:100px;cursor:pointer;}',
          '.settings-select:focus{border-color:VAR_PRIMARY_COLOR;}',
          '/* 与偏好设置页 el-input-number (controls-position=right) 一致的数字输入 */',
          '.settings-number{display:flex;align-items:stretch;height:26px;box-sizing:border-box;border:1px solid VAR_CONTROLS_BORDER;border-radius:VAR_CTRL_RADIUS;background-color:VAR_CONTROLS_BG;overflow:hidden;width:122px;}',
          '.settings-number-input{flex:1;min-width:0;border:none;background:transparent;color:VAR_TEXT_COLOR;font-size:12px;padding:0 6px;outline:none;text-align:center;}',
          '.settings-number-input::-webkit-outer-spin-button,.settings-number-input::-webkit-inner-spin-button{-webkit-appearance:none;margin:0;}',
          '.settings-number-ctrls{display:flex;flex-direction:column;width:22px;border-left:1px solid VAR_CONTROLS_BORDER;}',
          '.num-btn{flex:1;display:flex;align-items:center;justify-content:center;border:none;background:transparent;cursor:pointer;padding:0;margin:0;}',
          '.num-btn:hover{background-color:rgba(128,128,128,0.2);}',
          '.num-btn:active{background-color:rgba(128,128,128,0.35);}',
          '.tri-up{width:0;height:0;border-left:3.5px solid transparent;border-right:3.5px solid transparent;border-bottom:4px solid VAR_META_COLOR;}',
          '.tri-down{width:0;height:0;border-left:3.5px solid transparent;border-right:3.5px solid transparent;border-top:4px solid VAR_META_COLOR;}',
          '.settings-check{display:flex;align-items:center;gap:8px;margin:8px 0 8px 0;cursor:pointer;user-select:none;-webkit-user-select:none;}',
          '.settings-check input{width:14px;height:14px;accent-color:VAR_PRIMARY_COLOR;cursor:pointer;margin:0;}',
          '.settings-check span{font-size:12px;color:VAR_TEXT_COLOR;}',
          '.settings-save{height:26px;padding:0 18px;border-radius:VAR_CTRL_RADIUS;border:1px solid VAR_CONTROLS_BORDER;background-color:VAR_PRIMARY_COLOR;color:#fff;font-size:12px;cursor:pointer;}',
          '.settings-save:disabled{opacity:0.5;cursor:not-allowed;}',
          '.settings-save:hover:not(:disabled){opacity:0.9;}',
          '.settings-tip{font-size:11px;color:VAR_META_COLOR;}',
          '.pause-resume-group{display:flex;background-color:VAR_CONTROLS_BG;border-radius:VAR_CTRL_RADIUS;box-shadow:0 2px 8px rgba(0,0,0,0.15);border:1px solid VAR_CONTROLS_BORDER;overflow:hidden;position:relative;}',
          '.pause-resume-indicator{position:absolute;width:32px;height:32px;background-color:VAR_INDICATOR_BG;border-radius:VAR_CTRL_RADIUS;top:2px;left:2px;transition:transform 0.25s cubic-bezier(0.4, 0, 0.2, 1);z-index:0;box-shadow:inset 0 1px 3px rgba(0,0,0,0.1);}',
          '.pause-resume-indicator.right{transform:translateX(36px);}',
          '.pause-resume-group .controls-btn{border-radius:0;border:none;box-shadow:none;margin:0;background-color:transparent;width:36px;height:36px;position:relative;z-index:1;}',
          '.pause-resume-group .controls-btn:first-child{border-radius:VAR_CTRL_RADIUS 0 0 VAR_CTRL_RADIUS;}',
          '.pause-resume-group .controls-btn:last-child{border-radius:0 VAR_CTRL_RADIUS VAR_CTRL_RADIUS 0;}',
          '.controls-btn{width:36px;height:36px;border-radius:VAR_CTRL_RADIUS;border:none;background-color:VAR_CONTROLS_BG;cursor:pointer;display:flex;align-items:center;justify-content:center;padding:0;color:VAR_CONTROLS_ITEM_COLOR;transition:background-color .2s ease,opacity .2s ease;box-shadow:0 2px 8px rgba(0,0,0,0.15);border:1px solid VAR_CONTROLS_BORDER;}',
          '.controls-btn:hover:not(:disabled){background-color:VAR_CONTROLS_ITEM_HOVER_BG;}',
          '.pause-resume-group .controls-btn:hover:not(:disabled){background-color:transparent;color:VAR_PRIMARY_COLOR;}',
          '.controls-btn:disabled{cursor:not-allowed;opacity:0.4;}',
          '.controls-btn-icon{width:14px;height:14px;display:block;position:relative;}',
          '.icon-pause::before,.icon-pause::after{content:"";position:absolute;top:1px;bottom:1px;width:3px;border-radius:1px;background:currentColor;}',
          '.icon-pause::before{left:2px;}',
          '.icon-pause::after{right:2px;}',
          '.icon-resume::before{content:"";position:absolute;top:1px;bottom:1px;left:3px;border-style:solid;border-width:6px 0 6px 9px;border-color:transparent transparent transparent currentColor;}',
          '.icon-cancel::before,.icon-cancel::after{content:"";position:absolute;top:1px;bottom:1px;left:50%;width:2px;border-radius:1px;background:currentColor;transform-origin:center;}',
          '.icon-cancel::before{transform:translateX(-50%) rotate(45deg);}',
          '.icon-cancel::after{transform:translateX(-50%) rotate(-45deg);}',
          '.icon-connections{display:inline-block;width:14px;height:14px;position:relative;transition:transform .2s ease;}',
          '.icon-connections::before{content:"";position:absolute;width:0;height:0;border-style:solid;border-width:5px 5px 0 5px;border-color:currentColor transparent transparent transparent;left:2px;top:7px;}',
          '.icon-connections::after{content:"";position:absolute;width:2px;height:8px;background:currentColor;left:6px;top:3px;}',
          '.controls-btn.active .icon-connections{transform:rotate(180deg);}',
          '.icon-pin-svg{display:inline-block;width:14px;height:14px;transition:all .2s ease;margin-left:8px;}',
          '.controls-btn.active .icon-pin-svg{color:VAR_PRIMARY_COLOR;}'
        ].join('').replace(/VAR_BODY_BG/g, bodyBg)
          .replace(/VAR_TEXT_COLOR/g, textColor)
          .replace(/VAR_STATUS_COLOR/g, statusColor)
          .replace(/VAR_META_COLOR/g, metaColor)
          .replace(/VAR_BAR_BG/g, barBg)
          .replace(/VAR_CONTROLS_BG/g, controlsBg)
          .replace(/VAR_CONTROLS_BORDER/g, controlsBorder)
          .replace(/VAR_CONTROLS_DIVIDER/g, controlsDivider)
          .replace(/VAR_CONTROLS_ITEM_COLOR/g, controlsItemColor)
          .replace(/VAR_CONTROLS_ITEM_HOVER_BG/g, controlsItemHoverBg)
          .replace(/VAR_TITLE_BTN_HOVER_BG/g, titleBtnHoverBg)
          .replace(/VAR_INDICATOR_BG/g, indicatorBg)
          .replace(/VAR_CTRL_RADIUS/g, controlRadius)
          .replace(/VAR_PIECE_COLOR_0/g, tc.pieceColors[0])
          .replace(/VAR_PIECE_COLOR_1/g, tc.pieceColors[1])
          .replace(/VAR_PIECE_COLOR_2/g, tc.pieceColors[2])
          .replace(/VAR_PIECE_COLOR_3/g, tc.pieceColors[3])
          .replace(/VAR_PIECE_COLOR_4/g, tc.pieceColors[4])
          .replace(/VAR_PIECE_COLOR_5/g, tc.pieceColors[5] || tc.pieceColors[0])
          .replace(/VAR_TAB_BORDER/g, tc.tabBorder)
          .replace(/VAR_TAB_BG/g, tc.tabBg)
          .replace(/VAR_TAB_COLOR/g, tc.tabColor)
          .replace(/VAR_TAB_HOVER_BG/g, tc.tabHoverBg)
          .replace(/VAR_TAB_ACTIVE_BG/g, tc.tabActiveBg)
          .replace(/VAR_TAB_ACTIVE_COLOR/g, tc.tabActiveColor)
          .replace(/VAR_SUCCESS_COLOR/g, tc.successColor)
          .replace(/VAR_PRIMARY_COLOR/g, primaryColor)
        const html = [
          '<!DOCTYPE html>',
          '<html>',
          '<head>',
          '<meta charset="utf-8" />',
          '<title>Task Progress</title>',
          `<style>${styles}</style>`,
          '<style id="dynamic-theme-style"></style>',
          '</head>',
          '<body>',
          '<div class="title-bar">',
          '<div class="title-text" id="window-title"></div>',
          '<div class="title-actions"><button class="title-btn" id="min-btn">–</button><button class="title-btn" id="close-btn">×</button></div>',
          '</div>',
          '<div class="content">',
          '<div class="tab-content active" id="contentInfo">',
          '<div class="meta">',
          '<div class="meta-line" id="size"></div>',
          '<div class="meta-line" id="speed"></div>',
          '<div class="meta-line" id="avgSpeed"></div>',
          '<div class="meta-line" id="connections"></div>',
          '<div class="meta-line" id="remaining"></div>',
          '</div>',
          '</div>',
          '<div class="connections-panel" id="connectionsPanel" style="display:none;">',
          '<div class="conn-summary" id="connSummary">',
          '<div class="conn-summary-item"><div class="conn-summary-label" id="connTotalLabel"></div><div class="conn-summary-value" id="connTotalValue">0</div></div>',
          '<div class="conn-summary-item"><div class="conn-summary-label" id="connActiveLabel"></div><div class="conn-summary-value" id="connActiveValue">0</div></div>',
          '<div class="conn-summary-item"><div class="conn-summary-label" id="connSpeedLabel"></div><div class="conn-summary-value" id="connSpeedValue">0 B/s</div></div>',
          '</div>',
          '<div class="conn-table-wrap" id="connTableWrap">',
          '<table class="conn-table" id="connTable">',
          '<thead><tr><th id="connThHost"></th><th id="connThDownloaded"></th><th id="connThSpeed"></th><th id="connThStatus"></th></tr></thead>',
          '<tbody id="connTableBody"></tbody>',
          '</table>',
          '</div>',
          '<div class="conn-empty" id="connEmpty" style="display:none;"></div>',
          '</div>',
          '<div class="tab-content" id="contentPieces">',
          '<div class="pieces-scroll-wrap">',
          '<div class="pieces-scroll-box" id="piecesScrollBox">',
          '<div class="pieces-bar" id="piecesBar"></div>',
          '</div>',
          '<div class="pieces-empty" id="piecesEmpty" style="display:none;"></div>',
          '<div class="pieces-fade pieces-fade--top" id="piecesFadeTop" style="display:none;"></div>',
          '<div class="pieces-fade pieces-fade--bottom" id="piecesFadeBottom" style="display:none;"></div>',
          '</div>',
          '</div>',
          '<div class="tab-content" id="contentSettings">',
          '<div class="settings-panel" id="settingsPanel">',
          '<div class="settings-row" id="rowDownloadLimit">',
          '<span class="settings-label" id="labelDownloadLimit"></span>',
          '<div class="settings-number">',
          '<input class="settings-number-input" id="inputDownloadLimit" type="number" min="0" step="1" />',
          '<div class="settings-number-ctrls">',
          '<button type="button" class="num-btn" data-target="inputDownloadLimit" data-delta="1" tabindex="-1"><span class="tri-up"></span></button>',
          '<button type="button" class="num-btn" data-target="inputDownloadLimit" data-delta="-1" tabindex="-1"><span class="tri-down"></span></button>',
          '</div>',
          '</div>',
          '<select class="settings-select" id="unitDownloadLimit"><option value="K">KB/s</option><option value="M">MB/s</option></select>',
          '</div>',
          '<div class="settings-row" id="rowUploadLimit" style="display:none;">',
          '<span class="settings-label" id="labelUploadLimit"></span>',
          '<div class="settings-number">',
          '<input class="settings-number-input" id="inputUploadLimit" type="number" min="0" step="1" />',
          '<div class="settings-number-ctrls">',
          '<button type="button" class="num-btn" data-target="inputUploadLimit" data-delta="1" tabindex="-1"><span class="tri-up"></span></button>',
          '<button type="button" class="num-btn" data-target="inputUploadLimit" data-delta="-1" tabindex="-1"><span class="tri-down"></span></button>',
          '</div>',
          '</div>',
          '<select class="settings-select" id="unitUploadLimit"><option value="K">KB/s</option><option value="M">MB/s</option></select>',
          '</div>',
          '<label class="settings-check" id="rowCompletePopup">',
          '<input type="checkbox" id="checkCompletePopup" />',
          '<span id="labelCompletePopup"></span>',
          '</label>',
          '<div class="settings-row">',
          '<button class="settings-save" id="saveSettingsBtn"></button>',
          '<span class="settings-tip" id="unlimitedTip"></span>',
          '</div>',
          '</div>',
          '</div>',
          '</div>',
          // 进度条两层，与主窗口任务卡片 (TaskProgress.vue) 同一套语言：
          //   #bar      底条（下载进度 → 满格黄底"可以合并了" → 满格绿底"已完成"）
          //   #barCover 绿色覆盖层（合并进度，从 0 平滑盖到 100%）
          // 两层都是**常驻**元素，颜色/宽度只走 CSS 过渡，因此
          // "下载条 → 黄底 → 合并绿盖 → 绿底"全程平滑，不会瞬间跳。
          '<div class="bar-fixed"><div class="bar-inner" id="bar"></div><div class="bar-inner bar-inner--cover" id="barCover"></div></div>',
          '<div class="controls">',
          '<div class="controls-left">',
          '<button id="connToggle" class="controls-btn" title="连接详情"><span class="controls-btn-icon icon-connections"></span></button>',
          '<button id="pinBtn" class="controls-btn" title="固定窗口"><svg class="icon-pin-svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 14" width="14" height="14" fill="none"><path d="M 8.5 0.5 L 13.5 5.5 L 10.5 8.5 L 10 10.5 L 7.5 8 L 3.5 12 L 2.5 11 L 6.5 7 L 4 4.5 L 6 4 Z" fill="currentColor"/><circle cx="11" cy="3" r="1" fill="currentColor" opacity="0.35"/></svg></button>',
          '</div>',
          // 分段切换（信息/分片/设置）是**页签**：与左侧那组放在一起（相邻 8px，
          // 和右侧那组内部的间距一致）。放在最右侧的播放控制旁会让"页签 ↔ 左侧控件"
          // 之间出现一段可变的空白（窗口越窄越明显），看起来像间距不一致。
          '<div id="piecesToggle" class="pieces-toggle-group" style="display:none;">',
          '<div class="pieces-toggle-indicator" id="piecesToggleIndicator"></div>',
          '<button id="piecesTabInfo" class="pieces-toggle-tab active"></button>',
          '<button id="piecesTabPieces" class="pieces-toggle-tab"></button>',
          '<button id="piecesTabSettings" class="pieces-toggle-tab"></button>',
          '</div>',
          '<div class="controls-inner">',
          '<div class="pause-resume-group">',
          '<div class="pause-resume-indicator" id="pauseResumeIndicator"></div>',
          '<button id="pause" class="controls-btn" title="暂停"><span class="controls-btn-icon icon-pause"></span></button>',
          '<button id="resume" class="controls-btn" title="继续"><span class="controls-btn-icon icon-resume"></span></button>',
          '</div>',
          '<button id="cancel" class="controls-btn"><span class="controls-btn-icon icon-cancel"></span></button>',
          '</div>',
          '</div>',
          '<div id="hostTooltip" class="host-tooltip"></div>',
          '<script>',
          'const { ipcRenderer } = require("electron");',
          'let currentGid = "";',
          'let currentTab = "info";',
          'let cachedPiecesData = null;',
          '/* 进度条宽度只增不减（与主窗口任务卡片一致）：引擎分片校验失败重下、',
          '   统计口径抖动会让 percent 短暂回落，直接跟随会让进度条"倒退"；',
          '   只有回落超过 5 个百分点（重新选择文件、任务重新开始等真实变化）才回退 */',
          'let barPercentGid = "";',
          // 进度条动画与任务卡片 (TaskProgress.vue) **同一套**：250ms 定时器把
          // 显示值往「估计进度（最多领先 3 个点）」推进 40%，再由 CSS
          // width .4s cubic-bezier(.08,.82,.17,1) 抹平每一步。常量与算法来自
          // @shared/utils/progress-easing（唯一实现），由 buildProgressWindowHtml
          // 在生成 HTML 时注入 —— 不要在这个字符串脚本里另写一套。
          'const TICK_MS = ' + PROGRESS_TICK_MS + ';',
          '/* 上报进度（只增不减过滤后的目标值） */',
          'let barTargetPercent = null;',
          '/* 动画状态：显示值 + 按速度外推的锚点 */',
          'const anim = { display: null, total: 0, baseCompleted: 0, baseTime: 0, speed: 0, status: "", mergePercent: -1, recording: false };',
          'let pairPendingNow = false;',
          '/* 直播录制（引擎 isLive）：进度条不画百分比，走录制三态视觉',
          '   （与任务卡片同一套：录制中滚动斜纹 / 停住减速变灰 / 完成绿色铺满） */',
          'let currentIsLive = false;',
          '/* 斜纹相位（JS 逐帧推进）：速度指数渐变实现"逐渐停 / 逐渐动" */',
          'let recPhase = 0, recSpeed = 0, recRaf = null, recLastT = 0;',
          'function recTargetSpeed() {',
          '  return (currentIsLive && (`${anim.status}` === "active" || `${anim.status}` === "waiting")) ? 20 : 0;',
          '}',
          'function recApply() {',
          '  var v = (recPhase % 18).toFixed(2) + "px";',
          '  [document.querySelector(".bar"), document.querySelector(".bar-fixed")].forEach(function (el) {',
          '    if (el) el.style.setProperty("--lc-rec-phase", v);',
          '  });',
          '}',
          'function recSchedule() {',
          '  /* ⚠️ 不要在这里重置 recLastT —— recStep 每帧末尾都会回来调度下一帧，',
          '     每帧清一次会让 dt 恒为 0、速度永远涨不上去（相位不动）。',
          '     首帧的 dt 由 `recLastT ? … : 0` 自然处理；停后再启的第一帧',
          '     dt 被 Math.min(0.05,…) 夹住，仍是"逐渐"的。 */',
          '  if (recRaf == null && document.visibilityState !== "hidden") { recRaf = requestAnimationFrame(recStep); }',
          '}',
          'function recStep(t) {',
          '  recRaf = null;',
          '  var dt = recLastT ? Math.min(0.05, (t - recLastT) / 1000) : 0;',
          '  recLastT = t;',
          '  var tg = recTargetSpeed();',
          '  var k = 1 - Math.exp(-dt / 0.16);',
          '  recSpeed += (tg - recSpeed) * k;',
          '  if (Math.abs(recSpeed - tg) < 0.05) recSpeed = tg;',
          '  recPhase = (recPhase + recSpeed * dt) % 18;',
          '  recApply();',
          '  if (recSpeed > 0 || recTargetSpeed() > 0) recSchedule();',
          '}',
          'let barBaseColor = "";',
          /* 「一对音视频」的两个文件都下完之后：底条转成满格黄底（"可以合并了"），
             合并进度再用绿色覆盖层从左往右盖上去。合并进度只存在于渲染进程的
             mergeProgresses（由推送带下来），轮询**不带**该字段 —— 所以这里
             记住上一帧，不在合并中时才清零。 */
          'let mergeCoverPercent = 0;',
          'let currentMerged = false;',
          '/* 「一对音视频」折叠记录的成员 gid 与最近一次状态：',
          '   本窗口自身的 1Hz 轮询必须按同一批成员求和，否则推送（两条流的总量）',
          '   与轮询（画面流一条）会交替把进度条刷成两个数值。',
          '   合并期间（status = merging）也不能因为"引擎侧两条都下完了"就自关窗口。 */',
          'let currentPairGids = [];',
          '/* 窗口自己记住"这是一对音视频"。绝不能靠"引擎里能查到几条"来判断：',
          '   成员下完被引擎清理后只剩一条，靠查出来的条数就会把配对弄丢。 */',
          'let currentIsPair = false;',
          'let currentStatus = "";',
          '/* 推送路径给的名字（合并产物名）：轮询不该把它换回单条流的文件名 */',
          'let pushedTitle = "";',
          '/* 最近一次推送的完整 payload 与到达时刻。配对窗口的记录级字段一律以',
          '   推送为准（轮询只能看到引擎里还在的成员，成员被清理后它会给出单条流',
          '   的进度/大小/速度），推送断了才用轮询兜底。 */',
          'let lastPushPayload = null;',
          'let lastPushAt = 0;',
          '/* 状态进度条颜色：与主窗口 @shared/colors.json 完全一致（active #1a7fe0 等），',
          '   独立窗口进度条与任务卡片保持同一配色 */',
          'const STATUS_BAR_COLORS = {',
          '  active: "#1a7fe0",',
          '  waiting: "#737373",',
          '  paused: "#737373",',
          '  error: "#FF6157",',
          '  complete: "#2ACB42",',
          '  removed: "#737373",',
          '  seeding: "#2ACB42",',
          '  merging: "#E6A23C"',
          '};',
          /* ---- 进度条动画（与任务卡片 TaskProgress.vue 同一套算法） ----
             下面的函数体与常量来自 @shared/utils/progress-easing，由
             buildProgressWindowHtml 注入参数；改动画请改那个共享模块，
             两端（主列表 / 独立窗口）才会一直是同一个手感。 */
          'const BACKWARD_TOLERANCE = ' + PROGRESS_BACKWARD_TOLERANCE + ';',
          'const LEAD_MAX = ' + PROGRESS_LEAD_MAX + ';',
          'const LEAD_NEAR_DONE = ' + PROGRESS_LEAD_NEAR_DONE + ';',
          'const LEAD_ALMOST_DONE = ' + PROGRESS_LEAD_ALMOST_DONE + ';',
          'const NEAR_DONE_AT = ' + PROGRESS_NEAR_DONE_AT + ';',
          'const ALMOST_DONE_AT = ' + PROGRESS_ALMOST_DONE_AT + ';',
          'const EASE_ALPHA = ' + PROGRESS_EASE_ALPHA + ';',
          'function leadMaxFor(actual) {',
          '  var a = Number(actual);',
          '  if (!isFinite(a)) return LEAD_MAX;',
          '  if (a >= ALMOST_DONE_AT) return LEAD_ALMOST_DONE;',
          '  if (a >= NEAR_DONE_AT) return LEAD_NEAR_DONE;',
          '  return LEAD_MAX;',
          '}',
          'function easeToward(displayed, target) {',
          '  var d = Number(displayed), t = Number(target);',
          '  if (!isFinite(d)) return isFinite(t) ? t : 0;',
          '  if (!isFinite(t)) return d;',
          '  var next = d + (t - d) * EASE_ALPHA;',
          '  return next >= d ? next : d;',
          '}',
          'function applyReportedPercent(displayed, reported) {',
          '  var d = Number(displayed), r = Number(reported);',
          '  var value = isFinite(r) ? r : 0;',
          '  if (!isFinite(d)) return value;',
          '  if (value > d || d - value > BACKWARD_TOLERANCE) return value;',
          '  return d;',
          '}',
          /* 把当前显示值写进 DOM：底条（下载/待合并/已完成）+ 绿色合并覆盖层。
             两层都只改宽度/透明度，CSS 过渡负责补间（0.4s，与卡片一致）。 */
          'function renderProgressBar() {',
          '  if (!barEl) return;',
          '  if (anim.recording) {',
          '    /* 录制中：没有"进度"可言 —— 内条恒 0，动效交给 .is-recording 的斜纹 */',
          '    barEl.style.width = "0%";',
          '    barEl.style.opacity = "1";',
          '    if (barCoverEl) { barCoverEl.style.width = "0%"; }',
          '    return;',
          '  }',
          '  var shown = anim.display;',
          '  if (!isFinite(shown)) shown = 0;',
          '  barEl.style.width = (pairPendingNow ? 100 : Math.max(0, Math.min(100, shown))) + "%";',
          '  /* 绿色一出现就把底条调淡：满不透明的黄会压住绿色，读不出合并进度 */',
          '  barEl.style.opacity = mergeCoverPercent > 0 ? "0.4" : "1";',
          '  if (barCoverEl) {',
          '    barCoverEl.style.width = (pairPendingNow ? mergeCoverPercent : 0) + "%";',
          '  }',
          '}',
          'function animateProgressBar() {',
          '  if (barTargetPercent === null) return;',
          '  var actual = barTargetPercent;',
          '  /* 直播录制中：不画百分比、不按速度外推（没有总长这个分母） */',
          '  if (anim.recording) { anim.display = 0; renderProgressBar(); return; }',
          '  /* 非下载中：直接跟随（完成/合并 = 满格或合并进度；暂停/等待只增不减） */',
          '  if (anim.status !== "active") {',
          '    if (anim.status === "complete" || anim.status === "seeding") {',
          '      anim.display = 100;',
          '    } else if (anim.status === "merging") {',
          '      anim.display = anim.mergePercent >= 0 ? anim.mergePercent : 100;',
          '    } else {',
          '      anim.display = applyReportedPercent(isFinite(anim.display) ? anim.display : null, actual);',
          '    }',
          '    renderProgressBar();',
          '    return;',
          '  }',
          '  if (pairPendingNow) { anim.display = 100; renderProgressBar(); return; }',
          '  if (anim.display === null) { anim.display = actual; renderProgressBar(); return; }',
          '  var total = Number(anim.total);',
          '  if (!(anim.speed > 0) || !(anim.baseTime > 0) || !(total > 0)) {',
          '    if (actual > anim.display) { anim.display = actual; }',
          '    renderProgressBar();',
          '    return;',
          '  }',
          '  var elapsed = Math.max(0, Date.now() - anim.baseTime) / 1000;',
          '  var estCompleted = Math.min(anim.baseCompleted + anim.speed * elapsed, total);',
          '  var estPercent = (estCompleted / total) * 100;',
          '  anim.display = easeToward(anim.display, Math.min(estPercent, actual + leadMaxFor(actual), 100));',
          '  renderProgressBar();',
          '}',
          'let _piecesIndicatorW = 0;',
          'let _piecesIndicatorX = 0;',
          `let currentTheme = { tabBg: "${tc.tabBg}", tabColor: "${tc.tabColor}", tabBorder: "${tc.tabBorder}", tabActiveBg: "${tc.tabActiveBg}", tabActiveColor: "${tc.tabActiveColor}", barBg: "${tc.barBg}", pendingBarBg: "${tc.pendingBarBg}", pendingBarInner: "${tc.pendingBarInner}" };`,
          'const windowTitleEl = document.getElementById("window-title");',
          'const closeBtn = document.getElementById("close-btn");',
          'const minBtn = document.getElementById("min-btn");',
          'const piecesToggleGroup = document.getElementById("piecesToggle");',
          'const piecesToggleIndicator = document.getElementById("piecesToggleIndicator");',
          'const piecesTabInfoBtn = document.getElementById("piecesTabInfo");',
          'const piecesTabPiecesBtn = document.getElementById("piecesTabPieces");',
          'const piecesTabSettingsBtn = document.getElementById("piecesTabSettings");',
          'const contentInfoEl = document.getElementById("contentInfo");',
          'const contentConnectionsEl = document.getElementById("contentConnections");',
          'const contentPiecesEl = document.getElementById("contentPieces");',
          'const contentSettingsEl = document.getElementById("contentSettings");',
          'const settingsPanelEl = document.getElementById("settingsPanel");',
          'const rowDownloadLimitEl = document.getElementById("rowDownloadLimit");',
          'const rowUploadLimitEl = document.getElementById("rowUploadLimit");',
          'const rowCompletePopupEl = document.getElementById("rowCompletePopup");',
          'const labelDownloadLimitEl = document.getElementById("labelDownloadLimit");',
          'const labelUploadLimitEl = document.getElementById("labelUploadLimit");',
          'const labelCompletePopupEl = document.getElementById("labelCompletePopup");',
          'const inputDownloadLimitEl = document.getElementById("inputDownloadLimit");',
          'const inputUploadLimitEl = document.getElementById("inputUploadLimit");',
          'const unitDownloadLimitEl = document.getElementById("unitDownloadLimit");',
          'const unitUploadLimitEl = document.getElementById("unitUploadLimit");',
          'const checkCompletePopupEl = document.getElementById("checkCompletePopup");',
          'const saveSettingsBtnEl = document.getElementById("saveSettingsBtn");',
          'const unlimitedTipEl = document.getElementById("unlimitedTip");',
          'const connTotalLabelEl = document.getElementById("connTotalLabel");',
          'const connTotalValueEl = document.getElementById("connTotalValue");',
          'const connActiveLabelEl = document.getElementById("connActiveLabel");',
          'const connActiveValueEl = document.getElementById("connActiveValue");',
          'const connSpeedLabelEl = document.getElementById("connSpeedLabel");',
          'const connSpeedValueEl = document.getElementById("connSpeedValue");',
          'const connThHostEl = document.getElementById("connThHost");',
          'const connThDownloadedEl = document.getElementById("connThDownloaded");',
          'const connThSpeedEl = document.getElementById("connThSpeed");',
          'const connThStatusEl = document.getElementById("connThStatus");',
          'const connTableBodyEl = document.getElementById("connTableBody");',
          'const connEmptyEl = document.getElementById("connEmpty");',
          'const connTableWrapEl = document.getElementById("connTableWrap");',
          'const barEl = document.getElementById("bar");',
          'const barCoverEl = document.getElementById("barCover");',
          'const sizeEl = document.getElementById("size");',
          'const speedEl = document.getElementById("speed");',
          'const avgSpeedEl = document.getElementById("avgSpeed");',
          'const connectionsEl = document.getElementById("connections");',
          'const remainingEl = document.getElementById("remaining");',
          'const piecesBarEl = document.getElementById("piecesBar");',
          'const piecesEmptyEl = document.getElementById("piecesEmpty");',
          'const piecesScrollBoxEl = document.getElementById("piecesScrollBox");',
          'const piecesFadeTopEl = document.getElementById("piecesFadeTop");',
          'const piecesFadeBottomEl = document.getElementById("piecesFadeBottom");',
          'const pauseBtn = document.getElementById("pause");',
          'const resumeBtn = document.getElementById("resume");',
          'const cancelBtn = document.getElementById("cancel");',
          'const pauseResumeIndicator = document.getElementById("pauseResumeIndicator");',
          'const connToggleBtn = document.getElementById("connToggle");',
          'const connectionsPanel = document.getElementById("connectionsPanel");',
          'const hostTooltipEl = document.getElementById("hostTooltip");',
          'const PANEL_HEIGHT = 210;',
          'let isPanelOpen = false;',
          'let initialWidth = 0;',
          'let piecesDragState = null;',
          'let piecesFadeRafId = null;',
          'function updatePiecesFadeState() {',
          '  if (!piecesScrollBoxEl) return;',
          '  try {',
          '    const scrollH = piecesScrollBoxEl.scrollHeight || 0;',
          '    const clientH = piecesScrollBoxEl.clientHeight || 0;',
          '    if (scrollH <= clientH + 2) {',
          '      if (piecesFadeTopEl) piecesFadeTopEl.style.display = "none";',
          '      if (piecesFadeBottomEl) piecesFadeBottomEl.style.display = "none";',
          '      return;',
          '    }',
          '    const scrollTop = piecesScrollBoxEl.scrollTop || 0;',
          '    if (piecesFadeTopEl) piecesFadeTopEl.style.display = scrollTop > 2 ? "block" : "none";',
          '    const atBottom = scrollTop + clientH >= scrollH - 2;',
          '    if (piecesFadeBottomEl) piecesFadeBottomEl.style.display = atBottom ? "none" : "block";',
          '  } catch (_) {',
          '    if (piecesFadeTopEl) piecesFadeTopEl.style.display = "none";',
          '    if (piecesFadeBottomEl) piecesFadeBottomEl.style.display = "none";',
          '  }',
          '}',
          'function schedulePiecesFadeUpdate() {',
          '  if (piecesFadeRafId) return;',
          '  piecesFadeRafId = requestAnimationFrame(() => {',
          '    piecesFadeRafId = null;',
          '    updatePiecesFadeState();',
          '  });',
          '}',
          'if (piecesScrollBoxEl) {',
          '  piecesScrollBoxEl.addEventListener("scroll", schedulePiecesFadeUpdate);',
          '  piecesScrollBoxEl.addEventListener("mousedown", function(e) {',
          '    try {',
          '      const scrollH = piecesScrollBoxEl.scrollHeight || 0;',
          '      const clientH = piecesScrollBoxEl.clientHeight || 0;',
          '      if (scrollH <= clientH + 2) return;',
          '      piecesDragState = { startY: e.clientY, startScrollTop: piecesScrollBoxEl.scrollTop || 0 };',
          '      piecesScrollBoxEl.classList.add("is-dragging");',
          '      e.preventDefault();',
          '    } catch (_) {}',
          '  });',
          '  document.addEventListener("mousemove", function(e) {',
          '    if (!piecesDragState) return;',
          '    try {',
          '      const deltaY = e.clientY - piecesDragState.startY;',
          '      piecesScrollBoxEl.scrollTop = piecesDragState.startScrollTop - deltaY;',
          '    } catch (_) {}',
          '  });',
          '  document.addEventListener("mouseup", function() {',
          '    if (!piecesDragState) return;',
          '    piecesDragState = null;',
          '    if (piecesScrollBoxEl) piecesScrollBoxEl.classList.remove("is-dragging");',
          '  });',
          '}',
          'function hideHostTooltip() {',
          '  if (!hostTooltipEl) return;',
          '  hostTooltipEl.style.display = "none";',
          '}',
          'function showHostTooltip(text, x, y) {',
          '  if (!hostTooltipEl) return;',
          '  if (!text) { hideHostTooltip(); return; }',
          '  hostTooltipEl.innerText = text;',
          '  hostTooltipEl.style.display = "block";',
          '  hostTooltipEl.style.visibility = "hidden";',
          '  const padding = 8;',
          '  const offset = 12;',
          '  const maxX = Math.max(padding, window.innerWidth - hostTooltipEl.offsetWidth - padding);',
          '  const maxY = Math.max(padding, window.innerHeight - hostTooltipEl.offsetHeight - padding);',
          '  const left = Math.min(maxX, Math.max(padding, x + offset));',
          '  const top = Math.min(maxY, Math.max(padding, y + offset));',
          '  hostTooltipEl.style.left = left + "px";',
          '  hostTooltipEl.style.top = top + "px";',
          '  hostTooltipEl.style.visibility = "visible";',
          '}',
          'function updateHostTooltipFromEvent(e) {',
          '  try {',
          '    const target = e && e.target && e.target.closest ? e.target.closest(".conn-host") : null;',
          '    if (!target) { hideHostTooltip(); return; }',
          '    if (target.scrollWidth <= target.clientWidth + 1) { hideHostTooltip(); return; }',
          '    const text = target.innerText || "";',
          '    showHostTooltip(text, e.clientX, e.clientY);',
          '  } catch (err) {',
          '    hideHostTooltip();',
          '  }',
          '}',
          'if (connTableWrapEl) {',
          '  connTableWrapEl.addEventListener("mousemove", updateHostTooltipFromEvent);',
          '  connTableWrapEl.addEventListener("mouseleave", hideHostTooltip);',
          '  connTableWrapEl.addEventListener("scroll", hideHostTooltip);',
          '}',
          'ipcRenderer.invoke("get-progress-window-size").then((size) => {',
          '  if (size && size.width) {',
          '    initialWidth = size.width;',
          '  }',
          '}).catch(() => {});',
          'if (connToggleBtn) {',
          '  connToggleBtn.onclick = function() {',
          '    isPanelOpen = !isPanelOpen;',
          '    ipcRenderer.invoke("resize-progress-window", { isPanelOpen, panelHeight: PANEL_HEIGHT, initialWidth }).catch(() => {});',
          '    if (connectionsPanel) {',
          '      connectionsPanel.style.display = isPanelOpen ? "block" : "none";',
          '    }',
          '    if (connToggleBtn) {',
          '      connToggleBtn.classList.toggle("active", isPanelOpen);',
          '    }',
          '    hideHostTooltip();',
          '  };',
          '}',
          'const pinBtn = document.getElementById("pinBtn");',
          'let isPinned = false;',
          'if (pinBtn) {',
          '  pinBtn.onclick = function() {',
          '    isPinned = !isPinned;',
          '    pinBtn.classList.toggle("active", isPinned);',
          '    ipcRenderer.invoke("set-progress-window-always-on-top", isPinned).catch(() => {});',
          '  };',
          '}',
          'function updatePiecesIndicator() {',
          '  if (!piecesToggleIndicator) return;',
          '  /* 三个 tab 都要认：settings 落到 info 分支会导致滑块高亮停在"任务"上 */',
          '  var activeTab = currentTab === "pieces" ? piecesTabPiecesBtn',
          '    : (currentTab === "settings" ? piecesTabSettingsBtn : piecesTabInfoBtn);',
          '  if (!activeTab) return;',
          '  var w = activeTab.offsetWidth;',
          '  if (w > 0) {',
          '    var x = activeTab.offsetLeft;',
          '    var leftInset = 2;',
          '    var rightInset = 2;',
          '    w = w - leftInset - rightInset;',
          '    x = x + leftInset;',
          '    if (w !== _piecesIndicatorW) {',
          '      _piecesIndicatorW = w;',
          '      piecesToggleIndicator.style.width = w + "px";',
          '    }',
          '    if (x !== _piecesIndicatorX) {',
          '      _piecesIndicatorX = x;',
          '      piecesToggleIndicator.style.transform = "translateX(" + x + "px)";',
          '    }',
          '  }',
          '}',
          '/* 设置 tab 比信息 tab 需要更高内容区：切到设置拉高，切回收起。',
          '   窗口 resizable=false，高度完全由窗口逻辑控制 */',
          'function switchTab(tab) {',
          '  currentTab = tab;',
          '  if (piecesTabInfoBtn) piecesTabInfoBtn.classList.toggle("active", tab === "info");',
          '  if (piecesTabPiecesBtn) piecesTabPiecesBtn.classList.toggle("active", tab === "pieces");',
          '  if (piecesTabSettingsBtn) piecesTabSettingsBtn.classList.toggle("active", tab === "settings");',
          '  updatePiecesIndicator();',
          '  if (contentInfoEl) contentInfoEl.classList.toggle("active", tab === "info");',
          '  if (contentPiecesEl) contentPiecesEl.classList.toggle("active", tab === "pieces");',
          '  if (contentSettingsEl) contentSettingsEl.classList.toggle("active", tab === "settings");',
          '  if (tab === "pieces") { schedulePiecesFadeUpdate(); }',
          '  if (tab === "settings") { loadTaskSettings(); }',
          '}',
          'if (piecesTabInfoBtn) piecesTabInfoBtn.onclick = () => { switchTab("info"); };',
          'if (piecesTabPiecesBtn) piecesTabPiecesBtn.onclick = () => { switchTab("pieces"); };',
          'if (piecesTabSettingsBtn) piecesTabSettingsBtn.onclick = () => { switchTab("settings"); };',
          'if (minBtn) {',
          '  minBtn.onclick = () => {',
          '    try {',
          '      ipcRenderer.send("minimize-progress-window");',
          '    } catch (e) {',
          '      console.error("Failed to minimize window:", e);',
          '    }',
          '  };',
          '}',
          'if (closeBtn) {',
          '  closeBtn.onclick = () => {',
          '    try {',
          '      ipcRenderer.send("close-progress-window");',
          '    } catch (e) {',
          '      try { window.close(); } catch (err) {}',
          '    }',
          '  };',
          '}',
          'function sendAction(action) {',
          '  if (!currentGid) {',
          '    return;',
          '  }',
          '  ipcRenderer.send("command", "task-progress:control", { gid: currentGid, action });',
          '}',
          'if (pauseBtn) { pauseBtn.onclick = () => sendAction("pause"); }',
          'if (resumeBtn) { resumeBtn.onclick = () => sendAction("resume"); }',
          'if (cancelBtn) { cancelBtn.onclick = () => sendAction("cancel"); }',
          '/* ---- 设置分类：单任务限速 + 完成弹窗开关 ---- */',
          'let settingsLabels = { download: "", upload: "", save: "", saved: "", invalid: "", unlimitedTip: "", completePopup: "" };',
          'let isBTTask = false;',
          'let lastCompletePopupEnabled = undefined;',
          'let saveBtnRestoreTimer = null;',
          '/* 引擎限速值 → 表单。支持 "0" / "1024K" / "10M" / 纯字节数',
          '   （与全局设置 max-overall-*-limit 同形态，0 = 不限） */',
          'function parseLimitToUi(v) {',
          '  var s = String(v == null ? "0" : v).trim();',
          '  if (!s || s === "0") return { num: 0, unit: "K" };',
          '  var m = s.match(/^(\\d+(?:\\.\\d+)?)\\s*([KkMmGg]?)/);',
          '  if (!m) return { num: 0, unit: "K" };',
          '  var num = parseFloat(m[1]);',
          '  var unit = (m[2] || "").toUpperCase();',
          '  if (unit === "K") return { num: Math.round(num), unit: "K" };',
          '  if (unit === "M") return { num: num, unit: "M" };',
          '  if (unit === "G") return { num: Math.round(num * 1024 * 10) / 10, unit: "M" };',
          '  var bytes = num;',
          '  if (bytes >= 1048576) return { num: Math.round(bytes / 1048576 * 10) / 10, unit: "M" };',
          '  return { num: Math.max(1, Math.round(bytes / 1024)), unit: "K" };',
          '}',
          'function buildLimitValue(rawNum, unit) {',
          '  var n = parseFloat(rawNum);',
          '  if (isNaN(n) || n < 0) return null;',
          '  if (n === 0) return "0";',
          '  return "" + (Math.round(n * 10) / 10) + (unit === "M" ? "M" : "K");',
          '}',
          'function flashSaveBtn(text) {',
          '  if (!saveSettingsBtnEl) return;',
          '  if (saveBtnRestoreTimer) { clearTimeout(saveBtnRestoreTimer); saveBtnRestoreTimer = null; }',
          '  saveSettingsBtnEl.innerText = text;',
          '  saveBtnRestoreTimer = setTimeout(function() {',
          '    if (saveSettingsBtnEl) saveSettingsBtnEl.innerText = settingsLabels.save;',
          '    saveBtnRestoreTimer = null;',
          '  }, 2000);',
          '}',
          'function loadTaskSettings() {',
          '  if (!currentGid) return;',
          '  ipcRenderer.invoke("task-progress:get-option", { gid: currentGid }).then(function(res) {',
          '    if (!res || !res.success) return;',
          '    if (res.labels) settingsLabels = res.labels;',
          '    isBTTask = !!res.isBT;',
          '    if (labelDownloadLimitEl) labelDownloadLimitEl.innerText = settingsLabels.download;',
          '    if (labelUploadLimitEl) labelUploadLimitEl.innerText = settingsLabels.upload;',
          '    if (labelCompletePopupEl) labelCompletePopupEl.innerText = settingsLabels.completePopup;',
          '    if (saveSettingsBtnEl) saveSettingsBtnEl.innerText = settingsLabels.save;',
          '    if (unlimitedTipEl) unlimitedTipEl.innerText = settingsLabels.unlimitedTip;',
          '    if (rowUploadLimitEl) rowUploadLimitEl.style.display = isBTTask ? "flex" : "none";',
          '    var dl = parseLimitToUi(res.maxDownloadLimit);',
          '    var ul = parseLimitToUi(res.maxUploadLimit);',
          '    if (inputDownloadLimitEl) inputDownloadLimitEl.value = dl.num;',
          '    if (unitDownloadLimitEl) unitDownloadLimitEl.value = dl.unit;',
          '    if (inputUploadLimitEl) inputUploadLimitEl.value = ul.num;',
          '    if (unitUploadLimitEl) unitUploadLimitEl.value = ul.unit;',
          '    if (checkCompletePopupEl && lastCompletePopupEnabled !== undefined) {',
          '      checkCompletePopupEl.checked = !!lastCompletePopupEnabled;',
          '    }',
          '  }).catch(function() {});',
          '}',
          'function saveTaskSettings() {',
          '  if (!currentGid) return;',
          '  var options = {};',
          '  var dl = buildLimitValue(inputDownloadLimitEl ? inputDownloadLimitEl.value : 0, unitDownloadLimitEl ? unitDownloadLimitEl.value : "K");',
          '  if (dl === null) { flashSaveBtn(settingsLabels.invalid || "Error"); return; }',
          '  options["max-download-limit"] = dl;',
          '  if (isBTTask) {',
          '    var ul = buildLimitValue(inputUploadLimitEl ? inputUploadLimitEl.value : 0, unitUploadLimitEl ? unitUploadLimitEl.value : "K");',
          '    if (ul === null) { flashSaveBtn(settingsLabels.invalid || "Error"); return; }',
          '    options["max-upload-limit"] = ul;',
          '  }',
          '  ipcRenderer.invoke("task-progress:set-option", { gid: currentGid, options: options }).then(function(res) {',
          '    flashSaveBtn(res && res.success ? (settingsLabels.saved || "OK") : (settingsLabels.invalid || "Error"));',
          '  }).catch(function() { flashSaveBtn(settingsLabels.invalid || "Error"); });',
          '}',
          'if (saveSettingsBtnEl) saveSettingsBtnEl.onclick = saveTaskSettings;',
          '/* 数字步进按钮（对齐偏好设置页 el-input-number 的右侧上下箭头） */',
          '(function bindNumberSteppers() {',
          '  var btns = document.querySelectorAll(".num-btn");',
          '  if (!btns || !btns.length) return;',
          '  btns.forEach(function(btn) {',
          '    btn.addEventListener("click", function() {',
          '      var input = document.getElementById(btn.getAttribute("data-target"));',
          '      if (!input) return;',
          '      var delta = parseInt(btn.getAttribute("data-delta"), 10) || 0;',
          '      var v = parseFloat(input.value);',
          '      if (isNaN(v) || v < 0) v = 0;',
          '      v = Math.max(0, v + delta);',
          '      input.value = Math.round(v);',
          '    });',
          '  });',
          '})();',
          'if (checkCompletePopupEl) checkCompletePopupEl.addEventListener("change", function() {',
          '  ipcRenderer.send("command", "task-progress:set-complete-popup", { gid: currentGid, enabled: !!checkCompletePopupEl.checked });',
          '});',
          'ipcRenderer.on("task-progress-theme-update", (event, payload) => {',
          '  if (!payload) {',
          '    return;',
          '  }',
          '  const bodyBg = payload.bodyBg || "#ffffff";',
          '  const textColor = payload.textColor || "#2c3e50";',
          '  const statusColor = payload.statusColor || "#5a6c7d";',
          '  const metaColor = payload.metaColor || "#8492a6";',
          '  const barBg = payload.barBg || "#e2e8f0";',
          '  const controlsBg = payload.controlsBg || "#ffffff";',
          '  const controlsBorder = payload.controlsBorder || "#d3dde6";',
          '  const controlsDivider = payload.controlsDivider || "#e2e8f0";',
          '  const controlsItemColor = payload.controlsItemColor || "#5a6c7d";',
          '  const controlsItemHoverBg = payload.controlsItemHoverBg || "#f0f4f8";',
          '  const titleBtnHoverBg = payload.titleBtnHoverBg || "rgba(26,35,50,0.08)";',
          '  document.body.style.backgroundColor = bodyBg;',
          '  document.body.style.color = textColor;',
          '  if (piecesFadeTopEl) { piecesFadeTopEl.style.background = "linear-gradient(to bottom," + bodyBg + " 0%,transparent 100%)"; }',
          '  if (piecesFadeBottomEl) { piecesFadeBottomEl.style.background = "linear-gradient(to top," + bodyBg + " 0%,transparent 100%)"; }',
          '  const titleBarEl = document.querySelector(".title-bar");',
          '  if (titleBarEl) {',
          '    titleBarEl.style.backgroundColor = bodyBg;',
          '    titleBarEl.style.color = textColor;',
          '  }',
          '  const titleBtnEls = document.querySelectorAll(".title-btn");',
          '  if (titleBtnEls && titleBtnEls.length) {',
          '    titleBtnEls.forEach(el => {',
          '      el.style.color = textColor;',
          '    });',
          '  }',
          '  const metaEl = document.querySelector(".meta");',
          '  if (metaEl) {',
          '    metaEl.style.color = metaColor;',
          '  }',
          '  const barContainer = document.querySelector(".bar");',
          '  if (barContainer) {',
          '    barContainer.style.backgroundColor = barBg;',
          '  }',
          '  /* 进度条内条颜色不随主题覆盖：由 applyPayload 按任务状态统一',
          '     取 STATUS_BAR_COLORS（与主窗口任务卡片 colors[status] 一致），',
          '     避免主题更新把进度条刷成主题 barInner（绿色）后与卡片颜色分叉 */',
          '  const barFixedEl = document.querySelector(".bar-fixed");',
          '  if (barFixedEl) {',
          '    barFixedEl.style.backgroundColor = barBg;',
          '  }',
          '  const controlsEl = document.querySelector(".controls");',
          '  if (controlsEl) {',
          '    controlsEl.style.backgroundColor = bodyBg;',
          '  }',
          '  const pauseResumeGroupEl = document.querySelector(".pause-resume-group");',
          '  if (pauseResumeGroupEl) {',
          '    pauseResumeGroupEl.style.backgroundColor = controlsBg;',
          '    pauseResumeGroupEl.style.borderColor = controlsBorder;',
          '  }',
          '  const piecesToggleGroupEl = document.querySelector(".pieces-toggle-group");',
          '  if (piecesToggleGroupEl) {',
          '    piecesToggleGroupEl.style.backgroundColor = controlsBg;',
          '    piecesToggleGroupEl.style.borderColor = controlsBorder;',
          '  }',
          '  const dividerEls = document.querySelectorAll(".controls-divider");',
          '  if (dividerEls && dividerEls.length) {',
          '    dividerEls.forEach(el => {',
          '      el.style.backgroundColor = controlsDivider;',
          '    });',
          '  }',
          // 按钮颜色和背景已通过 dynamic-theme-style 管理，无需设置内联样式
          '  const styleEl = document.getElementById("dynamic-theme-style");',
          '  const primaryColor = payload.primaryColor || "#1a7fe0";',
          '  const pieceColors = payload.pieceColors || ["#ebedf0", "#9be9a8", "#40c463", "#30a14e", "#39d353", "#b9c4d2"];',
          '  if (styleEl) {',
          '    styleEl.textContent = ".title-btn:hover{background-color:" + titleBtnHoverBg + ";}.controls-btn{color:" + controlsItemColor + "!important;background-color:" + controlsBg + "!important;}.controls-btn:hover:not(:disabled){background-color:" + controlsItemHoverBg + "!important;}.pause-resume-group .controls-btn{background-color:transparent!important;}.pause-resume-group .controls-btn:hover:not(:disabled){background-color:transparent!important;color:" + primaryColor + "!important;}.pieces-toggle-tab{color:" + controlsItemColor + "!important;}.pieces-toggle-group .pieces-toggle-tab{background-color:transparent!important;}.pieces-toggle-tab:hover:not(.active){color:" + primaryColor + "!important;}.pieces-toggle-indicator{background-color:" + primaryColor + "!important;}.controls-left:hover .controls-btn{background-color:" + controlsItemHoverBg + "!important;}.controls-left:hover #pinBtn{background-color:" + controlsItemHoverBg + "!important;}.controls-btn.active .icon-pin-svg{color:" + primaryColor + "!important;}.piece.s0{background-color:" + pieceColors[0] + "!important;}.piece.s1{background-color:" + pieceColors[1] + "!important;}.piece.s2{background-color:" + pieceColors[2] + "!important;}.piece.s3{background-color:" + pieceColors[3] + "!important;}.piece.s4{background-color:" + pieceColors[4] + "!important;}.piece.s5{background-color:" + (pieceColors[5] || pieceColors[0]) + "!important;}";',
          '  }',
          '  const indicatorBg = payload.indicatorBg || "#e8e8e8";',
          '  if (pauseResumeIndicator) {',
          '    pauseResumeIndicator.style.backgroundColor = indicatorBg;',
          '  }',
          '  const connSummaryEl = document.querySelector(".conn-summary");',
          '  if (connSummaryEl) {',
          '    connSummaryEl.style.backgroundColor = barBg;',
          '  }',
          '  const connectionsPanelEl = document.querySelector(".connections-panel");',
          '  if (connectionsPanelEl) {',
          '    connectionsPanelEl.style.backgroundColor = bodyBg;',
          '  }',
          '  const connSummaryLabelEls = document.querySelectorAll(".conn-summary-label");',
          '  if (connSummaryLabelEls && connSummaryLabelEls.length) {',
          '    connSummaryLabelEls.forEach(el => {',
          '      el.style.color = metaColor;',
          '    });',
          '  }',
          '  const connSummaryValueEls = document.querySelectorAll(".conn-summary-value");',
          '  if (connSummaryValueEls && connSummaryValueEls.length) {',
          '    connSummaryValueEls.forEach(el => {',
          '      el.style.color = textColor;',
          '    });',
          '  }',
          '  const connTableThEls = document.querySelectorAll(".conn-table th");',
          '  if (connTableThEls && connTableThEls.length) {',
          '    const tabBg = payload.tabBg || "#f0f4f8";',
          '    const tabBorder = payload.tabBorder || "#d3dde6";',
          '    connTableThEls.forEach(el => {',
          '      el.style.backgroundColor = tabBg;',
          '      el.style.borderColor = tabBorder;',
          '      el.style.color = textColor;',
          '    });',
          '  }',
          '  const connTableTdEls = document.querySelectorAll(".conn-table td");',
          '  if (connTableTdEls && connTableTdEls.length) {',
          '    const tabBorder = payload.tabBorder || "#d3dde6";',
          '    connTableTdEls.forEach(el => {',
          '      el.style.borderColor = tabBorder;',
          '      if (!el.classList.contains("speed-active")) {',
          '        el.style.color = metaColor;',
          '      }',
          '    });',
          '  }',
          '  const connEmptyEl = document.querySelector(".conn-empty");',
          '  if (connEmptyEl) {',
          '    connEmptyEl.style.color = metaColor;',
          '  }',
          '  /* 设置面板：输入框容器/下拉/步进箭头跟随主题 */',
          '  const settingsBoxEls = document.querySelectorAll(".settings-number,.settings-select");',
          '  if (settingsBoxEls && settingsBoxEls.length) {',
          '    settingsBoxEls.forEach(el => {',
          '      el.style.backgroundColor = controlsBg;',
          '      el.style.borderColor = controlsBorder;',
          '    });',
          '  }',
          '  const settingsNumberEls = document.querySelectorAll(".settings-number-input");',
          '  if (settingsNumberEls && settingsNumberEls.length) {',
          '    settingsNumberEls.forEach(el => { el.style.color = textColor; });',
          '  }',
          '  const ctrlBorderEls = document.querySelectorAll(".settings-number-ctrls");',
          '  if (ctrlBorderEls && ctrlBorderEls.length) {',
          '    ctrlBorderEls.forEach(el => { el.style.borderLeftColor = controlsBorder; });',
          '  }',
          '  const triUpEls = document.querySelectorAll(".tri-up");',
          '  if (triUpEls && triUpEls.length) {',
          '    triUpEls.forEach(el => { el.style.borderBottomColor = metaColor; });',
          '  }',
          '  const triDownEls = document.querySelectorAll(".tri-down");',
          '  if (triDownEls && triDownEls.length) {',
          '    triDownEls.forEach(el => { el.style.borderTopColor = metaColor; });',
          '  }',
          '  const settingsMetaEls = document.querySelectorAll(".settings-label,.settings-tip");',
          '  if (settingsMetaEls && settingsMetaEls.length) {',
          '    settingsMetaEls.forEach(el => { el.style.color = metaColor; });',
          '  }',
          '  const settingsCheckTextEl = document.querySelector(".settings-check span");',
          '  if (settingsCheckTextEl) {',
          '    settingsCheckTextEl.style.color = textColor;',
          '  }',
          '  const tabBorder = payload.tabBorder || "#d3dde6";',
          '  /* 主题切换时同步待选择配色；保留 barBg（原先整体替换 currentTheme',
          '     会把 barBg/pending 配色丢掉，回落到浅色值导致深色下颜色不对） */',
          '  currentTheme = {',
          '    tabBorder,',
          '    tabActiveBg: payload.primaryColor || "#1a7fe0",',
          '    barBg: payload.barBg || currentTheme.barBg,',
          '    pendingBarBg: payload.pendingBarBg || currentTheme.pendingBarBg,',
          '    pendingBarInner: payload.pendingBarInner || currentTheme.pendingBarInner',
          '  };',
          '});',
          'function applyPayload(payload, source) {',
          '  if (!payload) {',
          '    return;',
          '  }',
          '  const fromPoll = source === "poll";',
          '  /* 只有真正的推送才刷新"最近一次推送"：配对窗口的合并重放（pair-merge）',
          '     不能刷新它，否则推送断流后它会自己把自己续命、永远不退回轮询兜底 */',
          '  if (source === "push") {',
          '    lastPushPayload = payload;',
          '    lastPushAt = Date.now();',
          '  }',
          '  if (payload.gid) {',
          '    const nextGid = String(payload.gid);',
          '    /* 换了记录：成员集合、配对标记与缓存的显示名一起重置，避免串台 */',
          '    if (currentGid && currentGid !== nextGid) {',
          '      currentPairGids = [];',
          '      currentIsPair = false;',
          '      pushedTitle = "";',
          '    }',
          '    currentGid = nextGid;',
          '  }',
          '  if (payload.isPair === true) {',
          '    currentIsPair = true;',
          '  }',
          '  /* 成员集合**只增不减**。轮询是按"引擎当前还查得到的成员"算的：某个成员',
          '     下完被引擎清理后它只回一条（甚至回空），照单全收就会让窗口"忘掉这是',
          '     一对"——之后按单条流算进度（于是与卡片的总进度每秒来回跳），并在那条',
          '     流下完时被主进程判成 done 而自行关窗（卡片却还在下载）。 */',
          '  if (Array.isArray(payload.pairGids) && payload.pairGids.length > 0) {',
          '    const mergedGids = currentPairGids.slice();',
          '    payload.pairGids.map(String).filter(Boolean).forEach(function (g) {',
          '      if (mergedGids.indexOf(g) === -1) { mergedGids.push(g); }',
          '    });',
          '    currentPairGids = mergedGids;',
          '    if (mergedGids.length > 1) { currentIsPair = true; }',
          '  }',
          '  if (currentPairGids.length === 0 && currentGid) {',
          '    currentPairGids = [currentGid];',
          '  }',
          '  /* 记录级字段（状态）在配对窗口里只认推送：主窗口持有折叠记录的聚合状态，',
          '     轮询只能看到引擎侧成员，成员一少就会回退成单条流的状态填上去。 */',
          '  if (!(fromPoll && currentIsPair) && payload.status) {',
          '    currentStatus = String(payload.status);',
          '  }',
          '  /* tab 切换组常显（设置 tab 常驻），首个 payload 到达即展示 */',
          '  if (piecesToggleGroup && piecesToggleGroup.style.display !== "flex") {',
          '    piecesToggleGroup.style.display = "flex";',
          '    requestAnimationFrame(updatePiecesIndicator);',
          '  }',
          '  /* 单任务"完成后弹窗"偏好缓存（切到设置 tab 时刷新 checkbox） */',
          '  if (payload.completePopupEnabled !== undefined) {',
          '    lastCompletePopupEnabled = payload.completePopupEnabled;',
          '  }',
          '  let title = payload.title ? String(payload.title) : "";',
          '  if (title && !fromPoll) { pushedTitle = title; }',
          '  /* 配对窗口的名字只认推送（折叠记录的产物名）。轮询回的是单条流',
          '     （画面流）的文件名，两条 1Hz 数据流交替写标题就是用户看到的',
          '     "窗口在两个任务的信息之间来回跳"。 */',
          '  if (fromPoll && currentIsPair) { title = pushedTitle; }',
          '  const percentText = payload.percentText ? String(payload.percentText) : "0%";',
          '  /* 配对窗口不能自己把标题写回单条流名字（含 document.title：Electron 会',
          '     用它覆盖系统窗口标题，1Hz 交替就是窗口标题在跳） */',
          '  if (title) {',
          '    try { document.title = title; } catch (e) {}',
          '  }',
          '  if (windowTitleEl) {',
          '    windowTitleEl.innerText = title;',
          '  }',
          '  if (piecesTabInfoBtn) {',
          '    if (payload.tabInfoShort !== undefined || payload.tabInfoText !== undefined) {',
          '      var infoShort = payload.tabInfoShort || payload.tabInfoText || "";',
          '      if (piecesTabInfoBtn.innerText !== infoShort) {',
          '        piecesTabInfoBtn.innerText = infoShort;',
          '        updatePiecesIndicator();',
          '      }',
          '      piecesTabInfoBtn.title = payload.tabInfoText || "";',
          '    }',
          '  }',
          '  if (piecesTabPiecesBtn) {',
          '    if (payload.tabPiecesShort !== undefined || payload.tabPiecesText !== undefined) {',
          '      var psShort = payload.tabPiecesShort || payload.tabPiecesText || "";',
          '      if (piecesTabPiecesBtn.innerText !== psShort) {',
          '        piecesTabPiecesBtn.innerText = psShort;',
          '        updatePiecesIndicator();',
          '      }',
          '      piecesTabPiecesBtn.title = payload.tabPiecesText || (payload.piecesData && payload.piecesData.tabText) || "";',
          '    }',
          '  }',
          '  if (piecesTabSettingsBtn) {',
          '    if (payload.tabSettingsShort !== undefined) {',
          '      if (piecesTabSettingsBtn.innerText !== payload.tabSettingsShort) {',
          '        piecesTabSettingsBtn.innerText = payload.tabSettingsShort;',
          '        updatePiecesIndicator();',
          '      }',
          '    }',
          '  }',
          '  if (barEl) {',
          '    /* 上报的进度只做"只增不减"过滤（percentText 仅作兜底解析） */',
          '    var rawPercent = Number(payload.percent);',
          '    if (!isFinite(rawPercent)) { rawPercent = parseFloat(percentText) || 0; }',
          '    rawPercent = Math.min(100, Math.max(0, rawPercent));',
          '    var percentGid = payload.gid ? String(payload.gid) : currentGid;',
          '    if (barPercentGid !== percentGid || barTargetPercent === null) {',
          '      barTargetPercent = rawPercent;',
          '      barPercentGid = percentGid;',
          '      anim.display = null;',
          '    } else {',
          '      barTargetPercent = applyReportedPercent(barTargetPercent, rawPercent);',
          '    }',
          '    /* 动画的输入：按速度外推需要原始字节数（与任务卡片同一套算法） */',
          '    var nTotal = Number(payload.totalLength != null ? payload.totalLength : NaN);',
          '    var nCompleted = Number(payload.completedLength != null ? payload.completedLength : NaN);',
          '    var nSpeed = Number(payload.downloadSpeed != null ? payload.downloadSpeed : NaN);',
          '    if (isFinite(nTotal) && isFinite(nCompleted) && (anim.total !== nTotal || anim.baseCompleted !== nCompleted)) {',
          '      anim.total = nTotal;',
          '      anim.baseCompleted = nCompleted;',
          '      anim.baseTime = Date.now();',
          '    }',
          '    anim.speed = isFinite(nSpeed) && nSpeed > 0 ? nSpeed : 0;',
          '    /* 与主窗口任务卡片 (TaskProgress.vue) 保持一致的"两层"画法：',
          '       底条 = 下载进度（配对且下完后是满格黄底 / 合并完是满格绿底），',
          '       覆盖层 = 绿色合并进度。两层都是常驻元素，只改宽度/颜色/透明度，',
          '       所以每一次切换都走 CSS 过渡，不会出现"直接跳"。 */',
          '    if (payload.merged !== undefined) { currentMerged = !!payload.merged; }',
          '    /* 直播录制：推送/轮询都带 isLive（推送为主、轮询兜底） */',
          '    if (payload.isLive !== undefined) { currentIsLive = !!payload.isLive; }',
          '    /* 直播"非完成态"（录制中与停住）：内条恒 0，动效交给录制斜纹 */',
          '    anim.recording = currentIsLive && `${payload.status || anim.status || ""}` !== "complete";',
          '    var mpRaw = Number(payload.mergePercent);',
          '    if (isFinite(mpRaw)) {',
          '      mergeCoverPercent = Math.min(100, Math.max(0, mpRaw));',
          '    } else if (`${payload.status || ""}` !== "merging") {',
          '      /* 不在合并中又没有任何上报 → 覆盖层必须清零（合并结束/换任务） */',
          '      mergeCoverPercent = 0;',
          '    }',
          '    /* 「待合并/合并中」由推送按字节口径判定（主进程只在推送断流兜底时补一个近似值）；',
          '       merged 兜一层，防止"已经合完"之后还停在黄底 */',
          '    pairPendingNow = payload.pairPending === true && !currentMerged;',
          '    anim.status = `${payload.status || ""}`;',
          '    anim.mergePercent = isFinite(mpRaw) ? Math.min(100, Math.max(0, mpRaw)) : -1;',
          '    var statusBarColor = STATUS_BAR_COLORS[payload.status] || STATUS_BAR_COLORS.active;',
          '    barBaseColor = payload.pendingSelection',
          '      ? (payload.pendingBarInner || currentTheme.pendingBarInner || "#f0ad4e")',
          '      : (pairPendingNow ? STATUS_BAR_COLORS.merging : statusBarColor);',
          '    barEl.style.backgroundColor = barBaseColor;',
          '    if (barCoverEl) { barCoverEl.style.backgroundColor = STATUS_BAR_COLORS.complete; }',
          '    renderProgressBar();',
          '  }',
          '  /* 待选择文件时进度为 0，内条没有宽度可言，底槽一并染色才看得出状态 */',
          '  var pendingTrackBg = payload.pendingSelection ? (payload.pendingBarBg || currentTheme.pendingBarBg || "#F6C46B") : (currentTheme.barBg || "#e2e8f0");',
          '  var liveStatusNow = `${payload.status || anim.status || ""}`;',
          '  var liveState = "";',
          '  if (currentIsLive) {',
          '    liveState = liveStatusNow === "complete" || liveStatusNow === "seeding"',
          '      ? "done"',
          '      : ((liveStatusNow === "active" || liveStatusNow === "waiting") ? "running" : "stopped");',
          '  }',
          '  [document.querySelector(".bar"), document.querySelector(".bar-fixed")].forEach(function (el) {',
          '    if (!el) return;',
          '    /* 录制三态：淡红底槽 / 暂停灰底槽 / 完成后交回主题底槽 */',
          '    el.style.backgroundColor = liveState === "running"',
          '      ? "rgba(245,108,108,0.16)"',
          '      : (liveState === "stopped" ? "rgba(115,115,115,0.14)" : pendingTrackBg);',
          '    el.classList.toggle("is-live", !!liveState);',
          '    el.classList.toggle("is-rec-stopped", liveState === "stopped");',
          '    el.classList.toggle("is-rec-done", liveState === "done");',
          '  });',
          '  /* 录制中拉起相位循环；停住/完成后不立刻停 —— 让速度渐变到 0（"逐渐停止"） */',
          '  if (liveState === "running" || recSpeed > 0) recSchedule();',
          '  if (liveState) recApply();',
          '  if (sizeEl && payload.sizeText != null) {',
          '    sizeEl.innerText = payload.sizeText || "";',
          '  }',
          '  if (speedEl && payload.speedText != null) {',
          '    speedEl.innerText = payload.speedText || "";',
          '  }',
          '  if (avgSpeedEl && payload.avgSpeedText != null) {',
          '    avgSpeedEl.innerText = payload.avgSpeedText || "";',
          '  }',
          '  if (connectionsEl && payload.connectionsText != null) {',
          '    connectionsEl.innerText = payload.connectionsText || "";',
          '  }',
          '  if (remainingEl && payload.remainingText != null) {',
          '    remainingEl.innerText = payload.remainingText || "";',
          '  }',
          '  if (payload.piecesData && payload.piecesData.numPieces > 0) {',
          '    const pd = payload.piecesData;',
          '    cachedPiecesData = pd;',
          '    if (piecesToggleGroup && piecesToggleGroup.style.display !== "flex") {',
          '      piecesToggleGroup.style.display = "flex";',
          '      requestAnimationFrame(updatePiecesIndicator);',
          '    }',
          '    if (piecesTabPiecesBtn) {',
          '      /* 分片数据到达：恢复可能被「无分片数据」帧隐藏的分片 tab。',
          '         三个 tab 是 flex:1 均分宽度（见 .pieces-toggle-tab），某个 tab 显隐',
          '         会改变**其余每个 tab 的宽度** ⇒ 滑块必须跟着重算，否则高亮条会停在',
          '         "两个 tab"时代的宽度上 —— 就是"分片分类出现时高亮长度没变、显示错位"。 */',
          '      if (piecesTabPiecesBtn.style.display === "none") {',
          '        piecesTabPiecesBtn.style.display = "";',
          '        requestAnimationFrame(updatePiecesIndicator);',
          '      }',
          '    }',
          '    if (piecesEmptyEl) {',
          '      piecesEmptyEl.style.display = "none";',
          '    }',
          '    if (piecesTabPiecesBtn && pd.tabText) {',
          '      piecesTabPiecesBtn.title = pd.tabText;',
          '    }',
          '    if (piecesBarEl && pd.pieces) {',
          '      const pieces = Array.from(piecesBarEl.querySelectorAll(".piece"));',
          '      const newPieces = pd.pieces;',
          '      const pieceCount = pieces.length;',
          '      const newPieceCount = newPieces.length;',
          '      for (let i = 0; i < newPieceCount; i++) {',
          '        const status = newPieces[i];',
          '        const cls = "s" + status;',
          '        if (i < pieceCount) {',
          '          const piece = pieces[i];',
          '          if (piece.className !== "piece " + cls) {',
          '            piece.className = "piece " + cls;',
          '          }',
          '        } else {',
          '          const newPiece = document.createElement("div");',
          '          newPiece.className = "piece " + cls;',
          '          piecesBarEl.appendChild(newPiece);',
          '        }',
          '      }',
          '      for (let i = pieceCount - 1; i >= newPieceCount; i--) {',
          '        pieces[i].remove();',
          '      }',
          '      schedulePiecesFadeUpdate();',
          '    }',
          '  } else {',
          '    cachedPiecesData = null;',
          '    /* 无分片数据（HTTP 任务）：只隐藏分片 tab，tab 组保留（设置 tab 常驻） */',
          '    if (piecesTabPiecesBtn && piecesTabPiecesBtn.style.display !== "none") {',
          '      piecesTabPiecesBtn.style.display = "none";',
          '      /* 隐藏同样改变其余 tab 的均分宽度 ⇒ 滑块要一起重算（同上） */',
          '      requestAnimationFrame(updatePiecesIndicator);',
          '    }',
          '    if (currentTab === "pieces") {',
          '      switchTab("info");',
          '    }',
          '    if (piecesBarEl) {',
          '      piecesBarEl.innerHTML = "";',
          '    }',
          '    if (piecesEmptyEl) {',
          '      piecesEmptyEl.innerText = payload.piecesEmptyText || "";',
          '      piecesEmptyEl.style.display = "block";',
          '    }',
          '  }',
          '  if (payload.connectionsData) {',
          '    const cd = payload.connectionsData;',
          '    if (connTotalLabelEl) connTotalLabelEl.innerText = cd.totalLabel || "";',
          '    if (connTotalValueEl) connTotalValueEl.innerText = cd.totalValue || "0";',
          '    if (connActiveLabelEl) connActiveLabelEl.innerText = cd.activeLabel || "";',
          '    if (connActiveValueEl) connActiveValueEl.innerText = cd.activeValue || "0";',
          '    if (connSpeedLabelEl) connSpeedLabelEl.innerText = cd.speedLabel || "";',
          '    if (connSpeedValueEl) connSpeedValueEl.innerText = cd.speedValue || "0 B/s";',
          '    if (connThHostEl) connThHostEl.innerText = cd.thHost || "";',
          '    if (connThDownloadedEl) connThDownloadedEl.innerText = cd.thDownloaded || "";',
          '    if (connThSpeedEl) connThSpeedEl.innerText = cd.thSpeed || "";',
          '    if (connThStatusEl) connThStatusEl.innerText = cd.thStatus || "";',
          '    if (cd.servers && cd.servers.length > 0) {',
          '      if (connTableWrapEl) connTableWrapEl.style.display = "block";',
          '      if (connEmptyEl) connEmptyEl.style.display = "none";',
          '      if (connTableBodyEl) {',
          '        const rows = Array.from(connTableBodyEl.querySelectorAll("tr"));',
          '        const newServers = cd.servers;',
          '        const rowCount = rows.length;',
          '        const serverCount = newServers.length;',
          '        for (let i = 0; i < serverCount; i++) {',
          '          const s = newServers[i];',
          '          if (i < rowCount) {',
          '            const row = rows[i];',
          '            const hostCell = row.cells[0];',
          '            const downloadedCell = row.cells[1];',
          '            const speedCell = row.cells[2];',
          '            const statusCell = row.cells[3];',
          '            if (hostCell) {',
          '              let hostSpan = hostCell.querySelector(".conn-host");',
          '              if (!hostSpan) {',
          '                hostCell.innerHTML = "<span class=\\"conn-host\\"></span>";',
          '                hostSpan = hostCell.querySelector(".conn-host");',
          '              }',
          '              const hostText = s.host || "-";',
          '              if (hostSpan) {',
          '                if (hostSpan.innerText !== hostText) hostSpan.innerText = hostText;',
          '                if (hostSpan.getAttribute("title") !== hostText) hostSpan.setAttribute("title", hostText);',
          '              }',
          '            }',
          '            if (downloadedCell && downloadedCell.innerText !== s.downloaded) downloadedCell.innerText = s.downloaded || "0 B";',
          '            if (speedCell) {',
          '              if (speedCell.innerText !== s.speed) speedCell.innerText = s.speed || "0 B/s";',
          '              const newClass = s.isActive ? "speed-active" : "";',
          '              if (speedCell.className !== newClass) speedCell.className = newClass;',
          '            }',
          '            if (statusCell && statusCell.innerText !== s.status) statusCell.innerText = s.status || "-";',
          '          } else {',
          '            const newRow = document.createElement("tr");',
          '            const hostTd = document.createElement("td");',
          '            const hostSpan = document.createElement("span");',
          '            const hostText = s.host || "-";',
          '            hostSpan.className = "conn-host";',
          '            hostSpan.innerText = hostText;',
          '            hostSpan.setAttribute("title", hostText);',
          '            hostTd.appendChild(hostSpan);',
          '            newRow.appendChild(hostTd);',
          '            const downloadedTd = document.createElement("td");',
          '            downloadedTd.innerText = s.downloaded || "0 B";',
          '            newRow.appendChild(downloadedTd);',
          '            const speedTd = document.createElement("td");',
          '            speedTd.className = s.isActive ? "speed-active" : "";',
          '            speedTd.innerText = s.speed || "0 B/s";',
          '            newRow.appendChild(speedTd);',
          '            const statusTd = document.createElement("td");',
          '            statusTd.innerText = s.status || "-";',
          '            newRow.appendChild(statusTd);',
          '            connTableBodyEl.appendChild(newRow);',
          '          }',
          '        }',
          '        for (let i = rowCount - 1; i >= serverCount; i--) {',
          '          rows[i].remove();',
          '        }',
          '      }',
          '    } else {',
          '      if (connTableBodyEl) {',
          '        connTableBodyEl.innerHTML = "";',
          '      }',
          '    }',
          '  }',
          '  if (pauseBtn) {',
          '    pauseBtn.title = payload.pauseText || "";',
          '    pauseBtn.disabled = !payload.canPause;',
          '  }',
          '  if (resumeBtn) {',
          '    resumeBtn.title = payload.resumeText || "";',
          '    resumeBtn.disabled = !payload.canResume;',
          '  }',
          '  if (pauseResumeIndicator) {',
          '    if (payload.isPaused) {',
          '      pauseResumeIndicator.classList.remove("right");',
          '    } else {',
          '      pauseResumeIndicator.classList.add("right");',
          '    }',
          '  }',
          '  if (cancelBtn) {',
          '    cancelBtn.title = payload.cancelText || "";',
          '    cancelBtn.disabled = !payload.canCancel;',
          '    cancelBtn.style.display = payload.showCancel ? \'flex\' : \'none\';',
          '  }',
          '}',
          '/* 轮询结果落到界面上之前先过一道"口径"过滤。',
          '   推送（主窗口按折叠记录算）与轮询（主进程只看引擎里还在的成员）是两条',
          '   独立 1Hz 数据流：对「一对音视频」来说只有推送能看到完整记录 —— 成员',
          '   下完被引擎清理后，轮询会回一条流的进度/大小/速度，两条流交替刷新就是',
          '   用户看到的"窗口信息在两个任务之间来回跳，而不是显示总进度"。',
          '   所以配对窗口里记录级字段一律用最近一次推送，轮询只补推送给不了的那',
          '   几项（平均速度、连接详情）；推送断流超过 4s 才退回完全跟随轮询。 */',
          'function applyPollPayload(payload) {',
          '  if (!payload) {',
          '    return;',
          '  }',
          '  const pushFresh = lastPushPayload && (Date.now() - lastPushAt) < 4000;',
          '  if (currentIsPair && pushFresh) {',
          '    const merged = Object.assign({}, lastPushPayload);',
          '    if (payload.avgSpeedText != null) { merged.avgSpeedText = payload.avgSpeedText; }',
          '    if (payload.connectionsData) { merged.connectionsData = payload.connectionsData; }',
          '    applyPayload(merged, "pair-merge");',
          '    return;',
          '  }',
          '  applyPayload(payload, "poll");',
          '}',
          'ipcRenderer.on("task-progress-update", (event, payload) => {',
          '  applyPayload(payload, "push");',
          '});',
          'async function pollProgress() {',
          '  if (!currentGid) {',
          '    return;',
          '  }',
          '  /* 窗口不可见（最小化/被遮挡）时无需刷新，恢复可见时会立即补拉一次 */',
          '  if (document.hidden) {',
          '    return;',
          '  }',
          '  const includeConnections = !!isPanelOpen;',
          '  /* 一对音视频：把整批成员 gid 一起发下去，让主进程按同一口径求和，',
          '     推送与轮询于是得到同一个"总进度"；合并期间即使引擎侧两条都下完',
          '     也不能自关窗口（合并还在跑，由主窗口在记录真正完成时关掉）。 */',
          '  const merging = currentStatus === "merging";',
          '  try {',
          '    const res = await ipcRenderer.invoke("task-progress:fetch", {',
          '      gid: currentGid,',
          '      gids: currentPairGids,',
          '      /* 把"这是一对"和窗口正在显示的名字一起带下去：主进程据此按同一批成员',
          '         求和、用同一个名字回填，不会因为某个成员已被引擎清理就退回单条流 */',
          '      isPair: currentIsPair,',
          '      title: pushedTitle,',
          '      includeConnections,',
          '      merging',
          '    });',
          '    if (res && res.done) {',
          '      /* 配对窗口不自行判定"完成"：成员可能已被引擎清理，只看引擎侧会把',
          '         "一条流下完"当成"这一对完成"。关窗交给主窗口 —— 它持有折叠记录',
          '         的聚合状态，记录真的完成/合并完时由它关闭本窗口。 */',
          '      if (!merging && !currentIsPair) {',
          '        try { window.close(); } catch (e) {}',
          '      }',
          '      return;',
          '    }',
          '    if (res && res.payload) {',
          '      applyPollPayload(res.payload);',
          '    }',
          '  } catch (e) {}',
          '}',
          'let pollTimer = setInterval(pollProgress, 1000);',
          /* 进度条动画定时器：与任务卡片 TaskProgress.vue 同一套（250ms 一步）。
             窗口不可见（最小化/被遮挡）时停掉，没有人看的时候不必空转。 */
          'let barTimer = setInterval(animateProgressBar, TICK_MS);',
          'document.addEventListener("visibilitychange", function() {',
          '  if (document.hidden) {',
          '    if (barTimer) { clearInterval(barTimer); barTimer = null; }',
          '  } else {',
          '    if (!barTimer) { barTimer = setInterval(animateProgressBar, TICK_MS); }',
          '    pollProgress();',
          '    animateProgressBar();',
          '  }',
          '});',
          '/* 滑块切换组常显，加载后初始化一次指示器位置 */',
          'requestAnimationFrame(updatePiecesIndicator);',
          'window.addEventListener("resize", () => { updatePiecesIndicator(); schedulePiecesFadeUpdate(); });',
          'window.addEventListener("beforeunload", () => {',
          '  try { if (pollTimer) clearInterval(pollTimer); } catch (e) {}',
          '  try { if (barTimer) clearInterval(barTimer); } catch (e) {}',
          '});',
          '</scr' + 'ipt>',
          '</body>',
          '</html>'
        ].join('')
        return html
      }
}
